name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.83.1'
      
      - name: Build Hugo Production Site
        run: hugo --minify

      - name: Deploy to S3
        run: hugo deploy
        env:
          AWS_ACCESS_KEY_ID: $
          AWS_SECRET_ACCESS_KeY: $

